# Generated by Django 4.2.11 on 2025-12-19 20:58

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuarios', '0005_userprofile_penalizaciones_acumuladas'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JobOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Título descriptivo del trabajo', max_length=200, verbose_name='Título')),
                ('description', models.TextField(help_text='Descripción detallada del trabajo requerido', verbose_name='Descripción')),
                ('budget_base_ars', models.DecimalField(decimal_places=2, help_text='Presupuesto base en pesos argentinos', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Presupuesto Base (ARS)')),
                ('status', models.CharField(choices=[('OPEN', 'Abierta'), ('IN_PROGRESS', 'En Progreso'), ('CLOSED', 'Cerrada')], db_index=True, default='OPEN', max_length=20, verbose_name='Estado')),
                ('is_consorcio', models.BooleanField(default=False, help_text='Indica si la oferta fue creada por un consorcio', verbose_name='Es Consorcio')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
                ('creator', models.ForeignKey(help_text='Perfil del usuario que crea la oferta (debe ser PERSONA o CONSORCIO)', on_delete=django.db.models.deletion.CASCADE, related_name='job_offers_created', to='usuarios.userprofile', verbose_name='Creador')),
            ],
            options={
                'verbose_name': 'Oferta de Trabajo',
                'verbose_name_plural': 'Ofertas de Trabajo',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Bid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_ars', models.DecimalField(decimal_places=2, help_text='Monto ofrecido en pesos argentinos', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Monto (ARS)')),
                ('estimated_days', models.PositiveIntegerField(help_text='Cantidad de días estimados para completar el trabajo', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Días Estimados')),
                ('pitch_text', models.TextField(help_text='Texto de presentación y propuesta del profesional', verbose_name='Propuesta')),
                ('is_active', models.BooleanField(default=True, help_text='Indica si la puja sigue siendo válida', verbose_name='Activa')),
                ('is_winner', models.BooleanField(default=False, help_text='Indica si esta puja fue seleccionada como ganadora', verbose_name='Ganadora')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
                ('job_offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bids', to='jobs.joboffer', verbose_name='Oferta de Trabajo')),
                ('professional', models.ForeignKey(help_text='Perfil del profesional que realiza la puja (debe ser OFICIO)', on_delete=django.db.models.deletion.CASCADE, related_name='bids_made', to='usuarios.userprofile', verbose_name='Profesional')),
            ],
            options={
                'verbose_name': 'Puja',
                'verbose_name_plural': 'Pujas',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Voto')),
                ('bid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='jobs.bid', verbose_name='Puja')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes_cast', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Voto',
                'verbose_name_plural': 'Votos',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['bid', '-created_at'], name='jobs_vote_bid_id_89cb74_idx'), models.Index(fields=['user', '-created_at'], name='jobs_vote_user_id_723508_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='vote',
            constraint=models.UniqueConstraint(fields=('user', 'bid'), name='unique_vote_per_user_per_bid'),
        ),
        migrations.AddIndex(
            model_name='joboffer',
            index=models.Index(fields=['status', '-created_at'], name='jobs_joboff_status_bdce53_idx'),
        ),
        migrations.AddIndex(
            model_name='joboffer',
            index=models.Index(fields=['creator', 'status'], name='jobs_joboff_creator_f35661_idx'),
        ),
        migrations.AddIndex(
            model_name='bid',
            index=models.Index(fields=['job_offer', '-created_at'], name='jobs_bid_job_off_9f9661_idx'),
        ),
        migrations.AddIndex(
            model_name='bid',
            index=models.Index(fields=['professional', '-created_at'], name='jobs_bid_profess_3e40fb_idx'),
        ),
        migrations.AddIndex(
            model_name='bid',
            index=models.Index(fields=['is_winner'], name='jobs_bid_is_winn_eecc0e_idx'),
        ),
        migrations.AddConstraint(
            model_name='bid',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('job_offer', 'professional'), name='unique_bid_per_professional_per_job'),
        ),
    ]
