# Generated by Django 4.2.11 on 2025-12-19 21:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='joboffer',
            name='expected_completion_date',
            field=models.DateTimeField(blank=True, help_text='Fecha esperada para completar el trabajo', null=True, verbose_name='Fecha de Finalización Esperada'),
        ),
        migrations.AddField(
            model_name='joboffer',
            name='is_delayed',
            field=models.BooleanField(db_index=True, default=False, help_text='Indica si el trabajo está atrasado respecto a la fecha esperada', verbose_name='Tiene Atraso'),
        ),
        migrations.AddField(
            model_name='joboffer',
            name='start_confirmed_date',
            field=models.DateTimeField(blank=True, help_text='Fecha en que se confirmó el inicio del trabajo', null=True, verbose_name='Fecha de Inicio Confirmada'),
        ),
        migrations.CreateModel(
            name='DelayRegistry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('days_delayed', models.PositiveIntegerField(help_text='Cantidad de días de atraso registrados', verbose_name='Días de Atraso')),
                ('reason', models.TextField(help_text='Explicación del profesional sobre las razones del atraso', verbose_name='Justificación del Atraso')),
                ('status', models.CharField(choices=[('PENDING', 'Pendiente de Revisión'), ('ACCEPTED', 'Aceptado por Cliente'), ('REJECTED', 'Rechazado por Cliente')], default='PENDING', help_text='Estado de la justificación', max_length=20, verbose_name='Estado')),
                ('accepted_by_client', models.BooleanField(default=False, help_text='Indica si el cliente aceptó la justificación del atraso', verbose_name='Aceptado por Cliente')),
                ('penalty_applied', models.BooleanField(default=False, help_text='Indica si se aplicó penalización al profesional', verbose_name='Penalización Aplicada')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('reviewed_at', models.DateTimeField(blank=True, help_text='Fecha en que el cliente revisó la justificación', null=True, verbose_name='Fecha de Revisión')),
                ('bid', models.ForeignKey(help_text='Propuesta/Bid asociada al atraso', on_delete=django.db.models.deletion.CASCADE, related_name='delay_registries', to='jobs.bid', verbose_name='Propuesta')),
                ('reviewed_by', models.ForeignKey(blank=True, help_text='Usuario que revisó la justificación', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delay_reviews', to=settings.AUTH_USER_MODEL, verbose_name='Revisado Por')),
            ],
            options={
                'verbose_name': 'Registro de Atraso',
                'verbose_name_plural': 'Registros de Atrasos',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['bid', '-created_at'], name='jobs_delayr_bid_id_f212df_idx'), models.Index(fields=['status', '-created_at'], name='jobs_delayr_status_693ee0_idx'), models.Index(fields=['accepted_by_client'], name='jobs_delayr_accepte_dfab3d_idx')],
            },
        ),
    ]
