# Generated by Django 4.2.11 on 2025-12-19 21:41

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0005_userprofile_penalizaciones_acumuladas'),
        ('jobs', '0002_joboffer_expected_completion_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EscrowTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_usdc', models.DecimalField(decimal_places=2, help_text='Monto en USDC de la transacción', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Monto (USDC)')),
                ('transaction_type', models.CharField(choices=[('INITIAL_DEPOSIT', 'Depósito Inicial (30%)'), ('REMAINING_DEPOSIT', 'Depósito Restante (70%)'), ('INITIAL_RELEASE', 'Liberación Inicial (30%)'), ('FINAL_RELEASE', 'Liberación Final (70% - 5%)'), ('PLATFORM_FEE', 'Comisión Plataforma (5%)'), ('REFUND', 'Reembolso')], max_length=30, verbose_name='Tipo de Transacción')),
                ('status', models.CharField(choices=[('LOCKED', 'Bloqueado en Escrow'), ('RELEASED', 'Liberado al Profesional'), ('REFUNDED', 'Reembolsado al Cliente')], default='LOCKED', max_length=20, verbose_name='Estado')),
                ('description', models.TextField(blank=True, help_text='Detalles de la transacción', verbose_name='Descripción')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Información adicional en formato JSON', verbose_name='Metadata')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
                ('released_at', models.DateTimeField(blank=True, help_text='Fecha en que se liberó el pago', null=True, verbose_name='Fecha de Liberación')),
                ('bid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='escrow_transactions', to='jobs.bid', verbose_name='Propuesta Aceptada')),
                ('from_wallet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='escrow_debits', to='usuarios.wallet', verbose_name='Wallet Origen')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='escrow_transactions', to='jobs.joboffer', verbose_name='Oferta de Trabajo')),
                ('to_wallet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='escrow_credits', to='usuarios.wallet', verbose_name='Wallet Destino')),
            ],
            options={
                'verbose_name': 'Transacción de Escrow',
                'verbose_name_plural': 'Transacciones de Escrow',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['job', '-created_at'], name='jobs_escrow_job_id_1cf1b7_idx'), models.Index(fields=['status', '-created_at'], name='jobs_escrow_status_112cea_idx'), models.Index(fields=['transaction_type'], name='jobs_escrow_transac_d8b368_idx')],
            },
        ),
    ]
