# Generated by Django 4.2.11 on 2025-12-19 15:14

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JobOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(help_text='Título descriptivo de la oferta', max_length=200, verbose_name='Título')),
                ('descripcion', models.TextField(blank=True, help_text='Descripción detallada del trabajo', verbose_name='Descripción')),
                ('zona', models.CharField(help_text='Zona geográfica donde se realizará el trabajo', max_length=255, verbose_name='Zona')),
                ('presupuesto_ars', models.DecimalField(decimal_places=2, help_text='Presupuesto estimado en pesos argentinos', max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Presupuesto (ARS)')),
                ('status', models.CharField(choices=[('ABIERTA', 'Abierta'), ('EN_PROGRESO', 'En Progreso'), ('FINALIZADA', 'Finalizada'), ('CANCELADA', 'Cancelada')], default='ABIERTA', max_length=20, verbose_name='Estado')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
                ('creador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ofertas_creadas', to=settings.AUTH_USER_MODEL, verbose_name='Creador')),
            ],
            options={
                'verbose_name': 'Oferta de Trabajo',
                'verbose_name_plural': 'Ofertas de Trabajo',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_rol', models.CharField(choices=[('PERSONA', 'Persona'), ('CONSORCIO', 'Consorcio'), ('OFICIO', 'Oficio')], default='PERSONA', max_length=20, verbose_name='Tipo de Rol')),
                ('zona', models.CharField(blank=True, help_text='Zona geográfica del usuario', max_length=255, null=True, verbose_name='Zona')),
                ('puntuacion', models.FloatField(default=0.0, help_text='Puntuación del usuario (0.0 - 5.0)', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(5.0)], verbose_name='Puntuación')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Perfil de Usuario',
                'verbose_name_plural': 'Perfiles de Usuarios',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='Proposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=2, help_text='Monto ofrecido por el profesional', max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Monto Propuesto (ARS)')),
                ('dias_entrega', models.PositiveIntegerField(help_text='Cantidad de días estimados para completar el trabajo', verbose_name='Días de Entrega')),
                ('comentario', models.TextField(blank=True, help_text='Detalles adicionales de la propuesta', verbose_name='Comentario')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
                ('version', models.PositiveIntegerField(default=1, help_text='Número de versión de la propuesta (contraofertas)', verbose_name='Versión')),
                ('oferta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='propuestas', to='usuarios.joboffer', verbose_name='Oferta de Trabajo')),
                ('profesional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='propuestas_enviadas', to=settings.AUTH_USER_MODEL, verbose_name='Profesional')),
            ],
            options={
                'verbose_name': 'Propuesta',
                'verbose_name_plural': 'Propuestas',
                'ordering': ['-fecha_actualizacion'],
                'unique_together': {('oferta', 'profesional')},
            },
        ),
    ]
