# Generated by Django 4.2.11 on 2025-12-19 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposal',
            name='voto_owner',
            field=models.BooleanField(default=False, help_text='Indica si el dueño de la oferta votó esta propuesta', verbose_name='Voto del Dueño'),
        ),
    ]
