# Generated by Django 4.2.11 on 2025-12-19 15:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('usuarios', '0002_proposal_voto_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='joboffer',
            name='fecha_entrega_pactada',
            field=models.DateTimeField(blank=True, help_text='Fecha comprometida para entregar el trabajo', null=True, verbose_name='Fecha de Entrega Pactada'),
        ),
        migrations.AddField(
            model_name='joboffer',
            name='fecha_entrega_real',
            field=models.DateTimeField(blank=True, help_text='Fecha en que se entregó el trabajo', null=True, verbose_name='Fecha de Entrega Real'),
        ),
        migrations.AddField(
            model_name='joboffer',
            name='fecha_inicio',
            field=models.DateTimeField(blank=True, help_text='Fecha en que se inició el trabajo', null=True, verbose_name='Fecha de Inicio'),
        ),
        migrations.CreateModel(
            name='DelayJustification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('replica', models.TextField(help_text='Explicación del profesional sobre el atraso', verbose_name='Réplica/Justificación')),
                ('dias_atraso_justificados', models.PositiveIntegerField(help_text='Cantidad de días de atraso que se están justificando', verbose_name='Días de Atraso')),
                ('penalizacion_omitida', models.BooleanField(default=False, help_text='Indica si el cliente aceptó la justificación y omitió la penalización', verbose_name='Penalización Omitida')),
                ('fecha_aceptacion', models.DateTimeField(blank=True, help_text='Fecha en que el cliente aceptó la justificación', null=True, verbose_name='Fecha de Aceptación')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
                ('aceptada_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='justificaciones_aceptadas', to=settings.AUTH_USER_MODEL, verbose_name='Aceptada Por')),
                ('oferta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='justificaciones_atraso', to='usuarios.joboffer', verbose_name='Oferta de Trabajo')),
                ('profesional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='justificaciones_enviadas', to=settings.AUTH_USER_MODEL, verbose_name='Profesional')),
            ],
            options={
                'verbose_name': 'Justificación de Atraso',
                'verbose_name_plural': 'Justificaciones de Atrasos',
                'ordering': ['-fecha_creacion'],
                'unique_together': {('oferta', 'profesional')},
            },
        ),
    ]
