# Generated by Django 4.2.11 on 2025-12-19 16:14

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('usuarios', '0003_joboffer_fecha_entrega_pactada_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_cuenta', models.CharField(choices=[('USER', 'Usuario'), ('ESCROW', 'Escrow Plataforma')], default='USER', max_length=20, verbose_name='Tipo de Cuenta')),
                ('balance_usdc', models.DecimalField(decimal_places=2, default=0.0, help_text='Saldo en USDC_MOCK (moneda simulada)', max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Balance USDC_MOCK')),
                ('nombre_cuenta', models.CharField(blank=True, help_text='Nombre descriptivo (ej: Plataforma_Escrow)', max_length=100, verbose_name='Nombre de Cuenta')),
                ('activa', models.BooleanField(default=True, verbose_name='Cuenta Activa')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
                ('user', models.OneToOneField(blank=True, help_text='Usuario propietario (null para cuentas del sistema)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='wallet', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Billetera',
                'verbose_name_plural': 'Billeteras',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto_usdc', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='Monto USDC')),
                ('tipo_transaccion', models.CharField(choices=[('ESCROW_DEPOSIT', 'Depósito a Escrow'), ('ESCROW_RELEASE', 'Liberación de Escrow'), ('PAYMENT', 'Pago'), ('REFUND', 'Reembolso'), ('FEE', 'Comisión Plataforma')], max_length=20, verbose_name='Tipo de Transacción')),
                ('status', models.CharField(choices=[('PENDING', 'Pendiente'), ('COMPLETED', 'Completada'), ('FAILED', 'Fallida'), ('REVERSED', 'Revertida')], default='PENDING', max_length=20, verbose_name='Estado')),
                ('descripcion', models.TextField(blank=True, help_text='Detalles de la transacción', verbose_name='Descripción')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Datos adicionales en formato JSON', verbose_name='Metadata')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Transacción')),
                ('from_wallet', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transacciones_enviadas', to='usuarios.wallet', verbose_name='Billetera Origen')),
                ('oferta_relacionada', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transacciones', to='usuarios.joboffer', verbose_name='Oferta Relacionada')),
                ('procesado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transacciones_procesadas', to=settings.AUTH_USER_MODEL, verbose_name='Procesado Por')),
                ('propuesta_relacionada', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transacciones', to='usuarios.proposal', verbose_name='Propuesta Relacionada')),
                ('to_wallet', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transacciones_recibidas', to='usuarios.wallet', verbose_name='Billetera Destino')),
            ],
            options={
                'verbose_name': 'Transacción',
                'verbose_name_plural': 'Transacciones',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='WorkEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_evento', models.CharField(choices=[('TRABAJO_INICIADO', 'Trabajo Iniciado'), ('TRABAJO_PAUSADO', 'Trabajo Pausado'), ('TRABAJO_REANUDADO', 'Trabajo Reanudado'), ('TRABAJO_COMPLETADO', 'Trabajo Completado'), ('TRABAJO_CANCELADO', 'Trabajo Cancelado'), ('PAGO_ESCROW', 'Pago Depositado en Escrow'), ('PAGO_LIBERADO', 'Pago Liberado al Profesional'), ('ATRASO_JUSTIFICADO', 'Atraso Justificado'), ('JUSTIFICACION_ACEPTADA', 'Justificación Aceptada')], max_length=30, verbose_name='Tipo de Evento')),
                ('descripcion', models.TextField(help_text='Detalles del evento', verbose_name='Descripción')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Datos adicionales del evento', verbose_name='Metadata')),
                ('fecha_evento', models.DateTimeField(auto_now_add=True, verbose_name='Fecha del Evento')),
                ('oferta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventos', to='usuarios.joboffer', verbose_name='Oferta de Trabajo')),
                ('transaccion_relacionada', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eventos', to='usuarios.transaction', verbose_name='Transacción Relacionada')),
                ('usuario_relacionado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eventos_generados', to=settings.AUTH_USER_MODEL, verbose_name='Usuario Relacionado')),
            ],
            options={
                'verbose_name': 'Evento de Trabajo',
                'verbose_name_plural': 'Eventos de Trabajos',
                'ordering': ['-fecha_evento'],
                'indexes': [models.Index(fields=['-fecha_evento'], name='usuarios_wo_fecha_e_116a69_idx'), models.Index(fields=['tipo_evento'], name='usuarios_wo_tipo_ev_4ffa88_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['-fecha_creacion'], name='usuarios_tr_fecha_c_aaf8ed_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['status'], name='usuarios_tr_status_16d76d_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['tipo_transaccion'], name='usuarios_tr_tipo_tr_11b659_idx'),
        ),
    ]
