# Generated by Django 4.2.11 on 2025-12-19 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_wallet_transaction_workevent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='penalizaciones_acumuladas',
            field=models.PositiveIntegerField(default=0, help_text='Número de penalizaciones por atrasos no justificados', verbose_name='Penalizaciones Acumuladas'),
        ),
    ]
