# Generated by Django 4.2.11 on 2025-12-19 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0005_userprofile_penalizaciones_acumuladas'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='cuit',
            field=models.CharField(blank=True, help_text='CUIT o CUIL del profesional', max_length=13, null=True, verbose_name='CUIT/CUIL'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='direccion',
            field=models.TextField(blank=True, help_text='Dirección del edificio o consorcio', null=True, verbose_name='Dirección'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='matricula',
            field=models.CharField(blank=True, help_text='Matrícula profesional (para administradores de consorcio)', max_length=100, null=True, verbose_name='Matrícula'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='rubro',
            field=models.CharField(blank=True, help_text='Especialidad del profesional (solo para Oficio)', max_length=100, null=True, verbose_name='Rubro'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='telefono',
            field=models.CharField(blank=True, help_text='Número de contacto del usuario', max_length=50, null=True, verbose_name='Teléfono'),
        ),
    ]
